packages:
  - "web"
  - "backend"

allowBuilds:
  azure-functions-core-tools: set this to true or false
  esbuild: set this to true or false

minimumReleaseAgeExclude:
  - '@aws-sdk/client-iam@3.1114.0'
  - '@aws-sdk/client-sts@3.1114.0'

onlyBuiltDependencies:
  - esbuild
  - azure-functions-core-tools
